;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cider-jack-in
        cider-load-buffer
        cljr-slash
        company-complete
        dabbrev-expand
        delete-horizontal-space
        hungry-delete-backward
        hungry-delete-forward
        indent-for-tab-command
        kill-rectangle
        kill-region
        move-frame-right
        mwim-beginning-of-code-or-line
        org-delete-char
        org-self-insert-command
        paredit-backward-slurp-sexp
        paredit-close-curly
        paredit-close-round
        paredit-close-square
        paredit-comment-dwim
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-open-curly
        paredit-open-round
        paredit-open-square
        paredit-semicolon
        paredit-splice-sexp
        upcase-region
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-mode
        ace-jump-move
        beginning-of-buffer
        helm-git-grep
        markdown-exdent-or-delete
        paredit-backward-kill-word
        paredit-kill
        ))
