;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        dabbrev-expand
        delete-horizontal-space
        kill-region
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-open-round
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        paredit-backward-kill-word
        paredit-kill
        ))
