alias ack=ack-grep
alias n=fortune
alias y=fortune
alias q=fortune
alias o=gnome-open
alias open=gnome-open
alias x='rxvt -rv -tr -sh 35 -sl 9999'
alias pg='LESS=-Xe psql'
alias cp='cp -i'
alias mv='mv -i'
alias df='df -h'
alias du='du -h'
alias ll='ls -l'
alias st='git st'
alias pull='git pull'
alias push='git push'
alias cls='clear'
alias gd='git diff'
alias syslog='tail -f /var/log/syslog'
alias slog='syslog'
alias b='git b'
alias co='git co'
alias merge='git merge'
