alias b='git b'
alias cls='clear'
alias co='git co'
alias cp='cp -i'
alias df='df -h'
alias du='du -h'
alias g='git'
alias gd='git diff'
alias ll='ls -l'
alias merge='git merge'
alias mv='mv -i'
alias n=fortune
alias o=gnome-open
alias open=gnome-open
alias pg='LESS=-Xe psql'
alias pull='git pull'
alias push='git push'
alias q=fortune
alias slog='syslog'
alias st='git st'
alias syslog='tail -f /var/log/syslog'
alias x='rxvt -rv -tr -sh 35 -sl 9999'
alias y=fortune
alias g=git
alias t=py.test
