"colorscheme desert
colorscheme darkblue
syntax on

" tab stop
set ts=4
" shift width
set sw=4

" Get rid of menubar, toolbar and all scrollbars
" set guioptions=melrb would turn them all back on
set guioptions=

" tabs to spaces
set expandtab

" highlighted unwanted whitespace in red
" the containedin=ALL ensures that it includes nested matches in other syntax groups
highlight ExtraWhitespace ctermbg=red guibg=red
autocmd Syntax * syn match ExtraWhitespace /\s\+$\| \+\ze\t/ containedin=ALL

" Watch vimrc for changes, from:
" http://stackoverflow.com/questions/2400264/is-it-possible-to-apply-vim-configurations-without-restarting/2403926#2403926
augroup myvimrc
    au!
    "I removed this from the pipeline below due to error
    "| so $MYGVIMRC
    au BufWritePost .vimrc,_vimrc,vimrc,.gvimrc,_gvimrc,gvimrc so $MYVIMRC | if has('gui_running') | endif
augroup END
