" Hide buffer instead of 'E37: No write since last change (add ! to override)'
set hidden

" For backup files
set backupdir=~/.vimbackups,/tmp
" For swap files
set directory=~/.vimswapfiles,/tmp

syntax on

" Don't ask if I want to reload files every 5 seconds
set autoread

" Make the window start big.
set lines=1000
set columns=1000

" Better tab expansion of filenames
set wildmenu

" enable spelling in general
"set spell spelllang=en_us
" but disable it for haskell source code
"autocmd FileType haskell setlocal nospell spelllang=en_us

" Keep pwd relative to current buffer
set autochdir

set tabstop=4
set shiftwidth=4

set visualbell

" Map underscore to remove search highlighting
nnoremap <silent> _ :nohl<CR>

" Preview markdown
:nnoremap <leader>m :silent !open -a Marked.app '%:p'<cr>

" Get rid of menubar, toolbar and all scrollbars
" set guioptions=melrb would turn them all back on
set guioptions=

" tabs to spaces
set expandtab

" show line numbers
set number

" show row,col in the bottom bar
set ruler

" show matching parens
set showmatch

set incsearch
set hlsearch

" enable plugins, e.g. snipmate
filetype plugin on

" enable the help
helptags ~/.vim/doc

" highlighted unwanted whitespace in red
" the containedin=ALL ensures that it includes nested matches in other syntax groups
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
highlight ExtraWhitespace ctermbg=red guibg=red
autocmd Syntax * syn match ExtraWhitespace /\s\+$\| \+\ze\t/ containedin=ALL

" Commenting for various programming languages
",c comments out a region
",u uncomments a region
au FileType haskell,vhdl,ada let b:comment_leader = '-- '
au FileType vim let b:comment_leader = '" '
au FileType c,cpp,java let b:comment_leader = '// '
au FileType sh,make let b:comment_leader = '# '
au FileType tex let b:comment_leader = '% '
noremap <silent> ,c :<C-B>sil <C-E>s/^/<C-R>=escape(b:comment_leader,'\/')<CR>/<CR>:noh<CR>
noremap <silent> ,u :<C-B>sil <C-E>s/^\V<C-R>=escape(b:comment_leader,'\/')<CR>//e<CR>:noh<CR>

" Watch vimrc for changes, from:
" http://stackoverflow.com/questions/2400264/is-it-possible-to-apply-vim-configurations-without-restarting/2403926#2403926
augroup myvimrc
    au!
    "I removed this from the pipeline below due to error
    "| so $MYGVIMRC
    au BufWritePost .vimrc,_vimrc,vimrc,.gvimrc,_gvimrc,gvimrc so $MYVIMRC | if has('gui_running') | endif
augroup END

" Enable pathogen
execute pathogen#infect()

" set colorscheme
" colorscheme sorcerer
" colorscheme hornet
" colorscheme darkBlue
colorscheme dark-ruby

let mapleader=","

" Unite
"nnoremap <C-p> :Unite file_rec/async<cr>
nnoremap <leader>f :<C-u>Unite -buffer-name=files file -no-split -start-insert<CR>
nnoremap <leader>b :<C-u>Unite -buffer-name=buffers buffer -no-split -start-insert<CR>
nnoremap <leader>l :set nolist!<CR>
