---
- name: "John's Standard OS X Development Environment"
  hosts: "John's Standard OS X Development Environment"
  remote_user: "john"

  vars:
    PostgresVersion: 9.3.5.2
    PostgresArchiveFn: Postgres-{{ PostgresVersion }}.zip
    PGInstallWorkDir: /tmp
    PostgresArchivePath: "{{ PGInstallWorkDir }}/{{ PostgresArchiveFn }}"

  tasks:

    - name: Add homebrew packages.
      homebrew:
        name={{ item }}
        update_homebrew=yes
        state=present
      with_items:
        - ack
#        - cowsay
        - curl
        - drake
        - cabal-install
        - erlang
#        - git  # "already installed" error... argh
        - go
        - gource
        - ghc
#        - jq  # "already installed" ...
#        - wget  # "already installed" ...

    # - name: Upgrade homebrew packages.
    #   homebrew:
    #     upgrade_all=yes

    - name: Ensure dotfiles checked out.
      git:
        dest=/Users/john/dotfiles
        force=no
        repo=git@github.com:lgastako/dotfiles.git

    - name: Get Postgres.app Archive.
      get_url:
        dest={{ PostgresArchivePath }}
        url="https://github.com/PostgresApp/PostgresApp/releases/download/{{ PostgresVersion }}/Postgres-{{ PostgresVersion }}.zip"
        force=no
