#source /usr/local/bin/virtualenvwrapper.sh


#source $HOME/dotfiles/oh-my-zsh/plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh

export PATH=/opt/local/bin:/opt/local/sbin:$PATH

# TODO - only if not already set?
#export JAVA_HOME=`/usr/libexec/java_home`


export PATH=/Users/john/dotfiles/google-cloud-sdk/bin:${PATH}
export PATH=/Users/john/.stack/snapshots/x86_64-osx/lts-7.13/8.0.1/bin:${PATH}