export AUTOBOT_PATTERN_PATHS="/Users/john/src/autobot-hs/patterns;/Users/john/src/refab/patterns"

eval "$(direnv hook zsh)"

# eval "$(~/.local/bin/mise activate zsh)"

alias corp='cd ~/src/ytmcnd/apps/john/droste/corp'

source <(fzf --zsh)

alias zed="open -a /Applications/Zed.app -n"

alias dayz="$HOME/src/arma3-unix-launcher/build/src/dayz-linux-launcher/dayz-linux-launcher"



export PATH="/opt/homebrew/opt/postgresql@16/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/postgresql@16/lib"
export CPPFLAGS="-I/opt/homebrew/opt/postgresql@16/include"

