export PATH=/usr/local/go/bin:$PATH

export DOCKER_HOST=tcp://10.10.10.10:4243

export DIALER_URL="http://john-asp.ngrok.io"


export SF_CONSUMER_KEY="3MVG9fMtCkV6eLhcuCTN3uTkdqQqKDqszwhZa_lYup4utmfd8cLOYt36nOwhgzadqtbvKcdplcH0Uagctz1Rf"
export SF_CONSUMER_SECRET="4703530024429242611"

